version: "3.9"
services:
  binancebot:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 80:80
    image: nyamkamunhjin/new-binance-bot
      
