name: Deploy binance bot

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build-docker:
    runs-on: self-hosted
    environment: Production
    steps:
      - uses: actions/checkout@v2
      - name: build and deploy
        run: |
          sudo touch .env
          sudo echo VARIABLE=${{ secrets.BINANCE_API_KEY }} >> .env
          sudo echo VARIABLE=${{ secrets.DISCORD_TOKEN }} >> .env
          sudo echo VARIABLE=${{ secrets.BINANCE_SECRET_KEY }} >> .env
          sudo echo VARIABLE=${{ secrets.PORT }} >> .env
          sudo docker-compose up -d --build
