name: Deploy binance bot

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build-docker:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: build and deploy
        run: |
          docker-compose up -d --build
